### ISSUE TITLE
Move Wiki articles to project site

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-glpi-demo#16]
Hi, @Naylin15 

Could you move this article to the Wiki in the project site?

https://github.com/flyve-mdm/flyve-mdm-glpi-demo/wiki/Self_create_an_user_account

Thank you.

**Comment by Naylin15** [comment]
Hi, @ajsb85 

This is done [9511e40](https://github.com/flyve-mdm/flyve-mdm-glpi-demo/commit/9511e40f7219ba5f07b3760cf69fde321d0f3bda)

**Comment by ajsb85** [comment]
Thanks
