### ISSUE TITLE
Lost password feature return a bad request status

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/flyve-mdm-glpi-demo#44]
Hi, @btry 
I got always an error when I try to recovery my password.

Reference:
https://github.com/flyve-mdm/web-mdm-dashboard/issues/665

**Comment by btry** [comment]
The backend could not find an account with your email address.

You had 2 accounts having the same email address, then the backend was unable to find only one account to reset.

One of your accounts had  2 email addresses. I removed the 2nd one which was already associated to the first account.

This is not a bug. Someone edited one of your accounts in a wrong way.
